loss_function: mutual_info

mutual_info_loss:
  estimator: variational
  density_estimator: flow
  dim_summary_fac: 2
  kwargs:
    num_hidden_layers: 2
    num_hidden_units: 64
    activation: relu
    num_layers: 4
    scale_eps: 1.0e-5
    log_scale_clip: 5.0
  regu:
    z_weight: null
