python ../../deep_lss/apps/run_training.py \
    --dir_base=$BASE \
    --dir_model=$MODEL \
    --loss_function=$LOSS \
    --train_tfr_pattern=$TRAIN_TFR \
    --grid_vali_tfr_pattern=$GRID_EVAL_TFR \
    --dlss_config="$PROJECT/y3-deep-lss/configs/$VERSION/default/$PROBE/dlss.yaml" \
    --net_config="$PROJECT/y3-deep-lss/configs/$VERSION/deepsphere_default.yaml" \
    --msfm_config="$PROJECT/multiprobe-simulation-forward-model/configs/$VERSION/$SUBVERSION.yaml" \
    --dist_strategy="$STRATEGY" \
    --mixed_precision