dset:
  common:
    with_lensing: False
    with_clustering: True
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [ Om, s8, w0, bg1, bg2, bg3, bg4 ]
  eval:
    fiducial:
      params: []
    grid:
      params: [ Om, s8, w0, bg1, bg2, bg3, bg4 ]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  clustering:
    # 24 Mpc/h transverse comoving scale
    theta_fwhm: [97.7, 66.7, 51.1, 42.8]
    white_noise_sigma: [0.76915, 0.34872, 0.34284, 0.35957]
    l_max: [178, 261, 340, 406]
