# contains the general, non model specific configuration parameters of the analysis
dset:
  common:
    with_lensing: True
    with_clustering: False
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [Om, s8, w0, Aia, n_Aia]
  eval:
    fiducial:
      params: []
    grid:
      params: [Om, s8, w0, Aia, n_Aia]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 6 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [22.1, 15.1, 11.2, 9.4]
    # 10 % noise threshold
    white_noise_sigma:
      [1.00118499e-03, 1.34439030e-03, 1.63581757e-03, 1.70957855e-03]
  clustering:
    # 16 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [65.1, 44.5, 34.1, 28.5]
    # 10 % noise threshold
    white_noise_sigma:
      [2.07311547e+00, 8.33123815e-01, 6.32685870e-01, 5.81933646e-01]

delta_loss:
  # regularization
  force_params_value: 0.0
  force_params_weight: 1.0
  jac_weight: 100.0
  jac_cond_weight: null
  cov_loss: False
  # numerical stability
  use_log_det: True
  tikhonov_regu: False
  eps: 1.0e-32
  # misc
  img_summary: False

likelihood_loss:
  # regularization
  lambda_tikhonov_init: 20.0
  lambda_tikhonov_decay_steps: 3000
  # misc
  img_summary: False

mutual_info_loss:
  estimator: "variational"
  dim_summary_fac: 2
  # Gaussian mixture model
  kwargs:
    num_components: 4
    num_hidden_layers: 2
    num_hidden_units: 128
    activation: "relu"
    full_covariance: True
