sbatch --nodes=1 --ntasks=4 submission.sh "delta" "1 node, 4 GPUs"
sbatch --nodes=2 --ntasks=8 submission.sh "delta" "2 nodes, 8 GPUs"
sbatch --nodes=4 --ntasks=16 submission.sh "delta" "4 nodes, 16 GPUs"
sbatch --nodes=8 --ntasks=32 submission.sh "delta" "8 nodes, 32 GPUs"
sbatch --nodes=16 --ntasks=64 submission.sh "delta" "16 nodes, 64 GPUs"
sbatch --nodes=32 --ntasks=128 submission.sh "delta" "32 nodes, 128 GPUs"

sbatch --nodes=1 --ntasks=4 submission.sh "likelihood" "1 node, 4 GPUs"
sbatch --nodes=2 --ntasks=8 submission.sh "likelihood" "2 nodes, 8 GPUs"
sbatch --nodes=4 --ntasks=16 submission.sh "likelihood" "4 nodes, 16 GPUs"
sbatch --nodes=8 --ntasks=32 submission.sh "likelihood" "8 nodes, 32 GPUs"
sbatch --nodes=16 --ntasks=64 submission.sh "likelihood" "16 nodes, 64 GPUs"
sbatch --nodes=32 --ntasks=128 submission.sh "likelihood" "32 nodes, 128 GPUs"
