# contains the general, non model specific configuration parameters of the analysis
dset:
  common:
    with_lensing: False
    with_clustering: True
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [Om, s8, w0, bg, n_bg]
  eval:
    fiducial:
      params: []
    grid:
      params: [Om, s8, w0, bg, n_bg]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 6 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [22.1, 15.1, 11.2, 9.4]
    # 1 % noise threshold, l_maxs = [786, 1150, 1535, 1535]
    white_noise_sigma: [2.3190e-04, 3.0898e-04, 4.1758e-04, 1.0030e-03]
  clustering:
    # 16 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [65.1, 44.5, 34.1, 28.5]
    # 1 % noise threshold, l_maxs = [267, 390, 509, 610]
    white_noise_sigma: [5.2009e-01, 2.0641e-01, 1.4949e-01, 1.3531e-01]

delta_loss:
  # regularization
  force_params_value: 0.0
  force_params_weight: 1.0
  jac_weight: 100.0
  jac_cond_weight: null
  cov_loss: False
  # numerical stability
  use_log_det: True
  tikhonov_regu: False
  eps: 1.0e-32
  # misc
  img_summary: False

likelihood_loss:
  # regularization
  lambda_tikhonov_init: 20.0
  lambda_tikhonov_decay_steps: 3000
  # misc
  img_summary: False

mutual_info_loss:
  estimator: "variational"
  dim_summary_fac: 2
  # Gaussian mixture model
  kwargs:
    num_components: 4
    num_hidden_layers: 2
    num_hidden_units: 128
    activation: "relu"
    full_covariance: True
