dset:
  common:
    with_lensing: True
    with_clustering: True
    with_cross_z: True
    with_cross_probe: True
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [ Om, s8, w0, Aia, n_Aia, bta, bg1, bg2, bg3, bg4 ]
  eval:
    fiducial:
      params: []
    grid:
      params: [ Om, s8, w0, Aia, n_Aia, bta, bg1, bg2, bg3, bg4 ]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 12 Mpc/h transverse comoving scale
    theta_fwhm: [44.3, 30.2, 22.5, 18.9]
    white_noise_sigma: [0.00041798, 0.00057273, 0.00071255, 0.00072769]
    l_max: [392, 575, 773, 921]
  clustering:
    # 32 Mpc/h transverse comoving scale
    theta_fwhm: [130.2, 88.9, 68.1, 57.0]
    white_noise_sigma: [0.98554, 0.43463, 0.42418, 0.44286]
    l_max: [133, 195, 255, 305]
