# contains the general, non model specific configuration parameters of the analysis
dset:
  common:
    with_lensing: False
    with_clustering: True
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [Om, s8, w0, bg1, bg2, bg3, bg4]
  eval:
    fiducial:
      params: []
    grid:
      params: [Om, s8, w0, bg1, bg2, bg3, bg4]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 12 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [44.3, 30.2, 22.5, 18.9]
    # 1 % noise threshold, l_maxs = [392, 575, 773, 921]
    white_noise_sigma: [4.1798e-04, 5.7273e-04, 7.1255e-04, 7.2769e-04]
    l_max: [392, 575, 773, 921]
  clustering:
    # 32 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [130.2, 88.9, 68.1, 57.0]
    # 1 % noise threshold, l_maxs = [133, 195, 255, 305]
    white_noise_sigma: [9.8554e-01, 4.3463e-01, 4.2418e-01, 4.4286e-01]
    l_max: [133, 195, 255, 305]

delta_loss:
  # regularization
  force_params_value: 0.0
  force_params_weight: 1.0
  jac_weight: 100.0
  jac_cond_weight: null
  cov_loss: False
  # numerical stability
  use_log_det: True
  tikhonov_regu: False
  eps: 1.0e-32
  # misc
  img_summary: False

likelihood_loss:
  # regularization
  lambda_tikhonov_init: 20.0
  lambda_tikhonov_decay_steps: 3000
  # misc
  img_summary: False

mutual_info_loss:
  estimator: "variational"
  dim_summary_fac: 2
  # Gaussian mixture model
  kwargs:
    num_components: 4
    num_hidden_layers: 2
    num_hidden_units: 128
    activation: "relu"
    full_covariance: True
  regu:
    z_weight: Null
