dset:
  common:
    with_lensing: True
    with_clustering: False
    with_cross_z: True
    with_cross_probe: False
    apply_norm: True
    return_maps: True
    return_cls: True
  training:
    params: [Om, s8, w0, Aia, n_Aia, bta]
  eval:
    fiducial:
      params: []
    grid:
      params: [Om, s8, w0, Aia, n_Aia, bta]
