# contains the general, non model specific configuration parameters of the analysis
dset:
  common:
    with_lensing: False
    with_clustering: True
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [Om, s8, w0, bg1, bg2, bg3, bg4, qbg1, qbg2, qbg3, qbg4]
  eval:
    fiducial:
      params: []
    grid:
      params: [Om, s8, w0, bg1, bg2, bg3, bg4, qbg1, qbg2, qbg3, qbg4]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 10 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [36.9, 25.2, 18.7, 15.7]
    # 10 % noise threshold, l_maxs = [333, 488, 656, 782]
    white_noise_sigma: [1.4892e-03, 2.0727e-03, 2.5265e-03, 2.6857e-03]
  clustering:
    # 28 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [113.9, 77.8, 59.6, 49.9]
    # 10 % noise threshold, l_maxs = [108, 158, 206, 246]
    white_noise_sigma: [3.1718e+00, 1.2253e+00, 9.8783e-01, 9.0101e-01]

delta_loss:
  # regularization
  force_params_value: 0.0
  force_params_weight: 1.0
  jac_weight: 100.0
  jac_cond_weight: null
  cov_loss: False
  # numerical stability
  use_log_det: True
  tikhonov_regu: False
  eps: 1.0e-32
  # misc
  img_summary: False

likelihood_loss:
  # regularization
  lambda_tikhonov_init: 20.0
  lambda_tikhonov_decay_steps: 3000
  # misc
  img_summary: False

mutual_info_loss:
  estimator: "variational"
  dim_summary_fac: 2
  # Gaussian mixture model
  kwargs:
    num_components: 4
    num_hidden_layers: 2
    num_hidden_units: 128
    activation: "relu"
    full_covariance: True
