estimator: variational

density_estimator: flow

# Head network architecture
num_hidden_layers: 2
num_hidden_units: 64
activation: relu

# Flow-specific
num_layers: 4
scale_eps: 1.0e-5
log_scale_clip: 5.0
