# contains the general, non model specific configuration parameters of the analysis
dset:
  common:
    with_lensing: True
    with_clustering: False
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [ Om, s8, w0, Aia, n_Aia, bta ]
  eval:
    fiducial:
      params: []
    grid:
      params: [ Om, s8, w0, Aia, n_Aia, bta ]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 14 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [ 51.6, 35.2, 26.2, 22.0 ]
    # 1 % noise threshold, l_maxs = [336, 493, 662, 789]
    white_noise_sigma: [ 4.6533e-4, 6.3996e-4, 8.0566e-4, 8.4511e-4 ]
    l_max: [ 336, 493, 662, 789 ]
  clustering:
    # 36 Mpc/h transverse comoving scale -> arcmin
    theta_fwhm: [ 146.5, 100.0, 76.6, 64.2 ]
    # 1 % noise threshold, l_maxs = [119, 174, 227, 271]
    white_noise_sigma: [ 1.0176e+0, 4.7044e-1, 4.773e-1, 4.9179e-1 ]
    l_max: [ 119, 174, 227, 271 ]

delta_loss:
  # regularization
  force_params_value: 0.0
  force_params_weight: 1.0
  jac_weight: 100.0
  jac_cond_weight: null
  cov_loss: False
  # numerical stability
  use_log_det: True
  tikhonov_regu: False
  eps: 1e-32
  # misc
  img_summary: False

likelihood_loss:
  # regularization
  lambda_tikhonov_init: 20.0
  lambda_tikhonov_decay_steps: 3000
  # misc
  img_summary: False

mutual_info_loss:
  estimator: "variational"
  dim_summary_fac: 2
  # Gaussian mixture model
  kwargs:
    num_components: 4
    num_hidden_layers: 2
    num_hidden_units: 128
    activation: "relu"
    full_covariance: True
  regu:
    z_weight:
      variance: Null
      covariance: Null
      invariance: 1.0
    z_type: vicreg
    z_layer: last
