dset:
  common:
    with_lensing: True
    with_clustering: True
    with_cross_z: True
    with_cross_probe: True
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [ Om, s8, w0, Aia, n_Aia, bta, bg1, bg2, bg3, bg4 ]
  eval:
    fiducial:
      params: []
    grid:
      params: [ Om, s8, w0, Aia, n_Aia, bta, bg1, bg2, bg3, bg4 ]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 14 Mpc/h transverse comoving scale
    theta_fwhm: [51.6, 35.2, 26.2, 22.0]
    white_noise_sigma: [0.00046533, 0.00063996, 0.00080566, 0.00084511]
    l_max: [336, 493, 662, 789]
  clustering:
    # 36 Mpc/h transverse comoving scale
    theta_fwhm: [146.5, 100.0, 76.6, 64.2]
    white_noise_sigma: [1.0176, 0.47044, 0.4773, 0.49179]
    l_max: [119, 174, 227, 271]
