dset:
  common:
    with_lensing: True
    with_clustering: False
    apply_norm: True
    return_maps: True
    return_cls: False
  training:
    params: [ Om, s8, w0, Aia, n_Aia, bta ]
  eval:
    fiducial:
      params: []
    grid:
      params: [ Om, s8, w0, Aia, n_Aia, bta ]

scale_cuts:
  n_sigma_support: 3
  arcmin: True
  lensing:
    # 10 Mpc/h transverse comoving scale
    theta_fwhm: [36.9, 25.2, 18.7, 15.7]
    white_noise_sigma: [0.00036488, 0.0004952, 0.00060135, 0.00062424]
    l_max: [471, 690, 927, 1105]
