# contains the model specific configuration parameters for training and hyperparameter optimization
name: deepsphere_default

training:
  n_steps: 100000
  output_every: 5000
  checkpoint_every: 10000
  vali_every: 5000
  eval_every: Null

optimization:
  # adam or sgd
  optimizer: adam
  # this could also be handled in the optimizer instead of the training step
  gradient_clipping:
    clip_by_value: null
    clip_by_norm: null
    clip_by_global_norm: 10.0
  delta_loss:
    # at the end of the warmup or from the beginning, if there is no schedule
    learning_rate: 1.0e-4
    # for beta_1, beta_2, epsilon, etc.
    optimizer_kwargs:
      beta_1: 0.9
      beta_2: 0.999
    # Null, "warmup" or "cosine" (which includes a warmup)
    scheduler: warmup
    warmup_steps: 5000
    warmup_init_learning_rate: 1.0e-5
    # for cosine schedule: alpha = decay_end_learning_rate / learning_rate
    decay_alpha: 0.0
    # linearly increase the noise amplitude from 0 to 1
    noise_schedule_steps: Null
  likelihood_loss:
    learning_rate: 1.0e-4
    optimizer_kwargs:
      beta_1: 0.9
      beta_2: 0.999
    scheduler: warmup
    warmup_steps: 5000
    warmup_init_learning_rate: 1.0e-5
    decay_alpha: 0.0
  mutual_info_loss:
    learning_rate: 1.0e-4
    optimizer_kwargs:
      beta_1: 0.9
      beta_2: 0.999
    scheduler: warmup
    warmup_steps: 5000
    warmup_init_learning_rate: 1.0e-5
    decay_alpha: 0.0

network:
  name: resnet
  n_neighbors: 60
  max_checkpoints: 20
  save_second_to_last_layer: False
  kwargs:
    base_channels: 32
    # depth
    downsampling_layers: 3
    cheby_layers: 2
    residual_layers: 6
    # misc
    poly_degree: 5
    head_type: "dense"
    second_to_last_features: Null
    dropout_rate: 0.01

dset:
  training:
    common:
      is_eval: False
      n_readers: 8
      n_prefetch: 2
      n_workers: 96
    # delta loss
    fiducial:
      noise_indices: 10
      # because of the derivatives, this is multiplied by 1 + 2 * n_params
      local_batch_size: 4
      file_name_shuffle_buffer: 64
      examples_shuffle_buffer: 128
      is_cached: False
    # mutual info, likelihood, mse loss
    grid:
      noise_indices: 4
      local_batch_size: 32
      file_name_shuffle_buffer: 64
      examples_shuffle_buffer: 128
  eval:
    common:
      is_eval: True
      local_batch_size: 32
    validation:
      noise_indices: 10
      n_prefetch: 0
      n_readers: 1
      n_workers: 8
      is_cached: False
      drop_remainder: True
    fiducial:
      noise_indices: 10
      n_prefetch: 1
      n_workers: 8
      n_readers: 2
      is_cached: False
    grid:
      noise_indices: [4]
      n_prefetch: 1
      n_workers: 16
      n_readers: 32
